### ISSUE TITLE
Update to .Net Core 2.0 or .Net Standard 2.0

### ISSUE THREAD

**Issue by Chris-ZA** [refactorsaurusrex/FluentConsole#13]
Hi,

I just stumbled across this and it's perfect for a little project I'm working on.  Nice work!  

My only issue is that the console app I'm working on is a .Net Core app so I'm getting the following warning in Visual Studio.

    Warning NU1701 
    Package 'FluentConsole.Library 1.0.54' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'.
    This package may not be fully compatible with your project.

Any plans to update it to .Net Core 2.0 or .Net Standard 2.0?

I'm pretty sure updating it to .Net Standard will be fairly simple and am happy to give it a crack and submit a pull request if you want.

Regards,

Chris

**Comment by refactorsaurusrex** [comment]
Hey Chris,

I do have _plans_ to update this to work with .NET core... but what I haven't had for a while now is time to actually do it. (Damn day jobs!! lol) If you have the time, I'd happily accept a PR!

Nick

**Comment by Chris-ZA** [comment]
Cool.  I've created a fork and will submit something over the next few days.

Would you prefer that I target .Net Standard so it works with .Net Framework and .Net Core?

Also, what versions do you want to use?  2.0?

Regards,

Chris

**Comment by refactorsaurusrex** [comment]
Completed in version 2.0.4! 💥
