### ISSUE TITLE
Plans to support format strings?

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [refactorsaurusrex/FluentConsole#2]
Neat little lib, i was wondering if you had plans to support formatted strings.

**Comment by refactorsaurusrex** [comment]
No current plans. Do you have a use case in mind that the example below wouldn't be appropriate for? If so, I'd be curious to know.

```
var firstName = "Nick";
var lastName = "Spreitzer";

// C# >= 6
$"My first name is '{firstName}' and my last name is '{lastName}'.".WriteLine();

// C# < 6
string.Format("My first name is '{0}' and my last name is '{1}'.", firstName, lastName)
    .WriteLineWait();
```

**Comment by AlgorithmsAreCool** [comment]
No specific use case, I just think it would be a tiny bit easier with a couple overloads for C# 5 and below. I could write then in a PR if you think it's a good idea.

**Comment by refactorsaurusrex** [comment]
Can you show me an example of the potential usage? Are thinking something like this?

```
"My first name is '{0}' and my last name is '{1}'.".WriteLine("Nick", "Spreitzer");
```

**Comment by AlgorithmsAreCool** [comment]
I thought about this again this morning and i think that the C# 6 syntax does everything already including numerical formatting ( e.g. `{myNum:N0}` ) which i didn't realize. I think now this change is unnecessary.

**Comment by refactorsaurusrex** [comment]
I actually think it was a good idea, for those who aren't on C# 6 yet. I may still implement the example I wrote above.
