### ISSUE TITLE
JQuery-style writing

### ISSUE THREAD

**Issue by Lucidiot** [refactorsaurusrex/FluentConsole#8]
I thought of a new feature that could be useful to shorten code writing even more :
`Console.WriteLine("text", ConsoleColor.Red).WriteLineWait("more text").`
Methods could return a Console instance, allowing to use more methods on a single line.
I'm still trying to determine if it's technically possible, and am not sure about all its details at all, but that's an idea I came up with.

**Comment by refactorsaurusrex** [comment]
Thanks for the idea! I'll keep in mind. :-)
